### ISSUE TITLE
not able to load extra scripts in config.coffee

### ISSUE THREAD

**Issue by mwagena** [scotch/angular-brunch-seed#54]
Seems like it's skipping the extra files added in the vendor directory

**Comment by kylefinley** [comment]
@mwagena,

Thanks for reporting this. I believe what you are experiencing is due to the switch to Bower. There were some unintended consequences of this change, we are working to get them sorted out. In the mean time could you move the scripts to the app directory, or create a [Bower package](http://twitter.github.com/bower/) for the files? I'll update this issue when the problem is resolved.

Kyle

**Comment by mwagena** [comment]
@kylefinley 
Thanks for your reaction, for now i'm using a older build of the repo.
Seeing forward to an updated version!

**Comment by nathanredblur** [comment]
You can try this. Put your js file in a folder on Vendor, then run this command : bower init

**Comment by kylefinley** [comment]
Commit 4cffcba08874a5b101fb0ffd9b85f63576804ff6 (v0.4.0) adds native bower support, and moves bower components to `bower_components` so the old vendor settings should work now. 

Please let me know if your still having problems after you upgrade.
